apiVersion: monitor.cluster-tools.dev/v1alpha1
kind: StatefulSetHealer
metadata:
  labels:
    app.kubernetes.io/name: stshealer
    app.kubernetes.io/managed-by: kustomize
  name: statefulsethealer
spec:
  targetRef:
    name: demo-db
  maxRestartAttempts: 3
  failureTimeThreshold: 5s